import argparse
import sys
from pathlib import Path

import torch
import torchvision.utils as vutils


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Peek at faces in .pt files generated by preprocessing"
    )
    parser.add_argument(
        "--input-path",
        type=str,
        help="Path to .pt file or directory containing .pt files",
    )
    parser.add_argument(
        "--output", "-o", type=str, default="preview.png", help="Output image file path"
    )
    parser.add_argument(
        "--nrow", type=int, default=8, help="Number of images per row in the grid"
    )
    parser.add_argument(
        "--max-frames",
        type=int,
        default=64,
        help="Maximum number of frames to visualize",
    )
    parser.add_argument(
        "--random",
        action="store_true",
        help="Select random frames instead of the first ones",
    )

    args = parser.parse_args()

    input_path = Path(args.input_path)

    if input_path.is_dir():
        print(f"Input is a directory: {input_path}")
        files = sorted(list(input_path.glob("*_faces.pt")))
        if not files:
            print("No *_faces.pt files found in directory.")
            return
        print("Found files:")
        for _, f in enumerate(files[:10]):
            print(f"  {f.name}")
        if len(files) > 10:
            print(f"  ... and {len(files) - 10} more.")

        print("\nPlease specify a file path to visualize one of them.")
        return

    if not input_path.exists():
        print(f"File not found: {input_path}")
        sys.exit(1)

    try:
        print(f"Loading {input_path}...")
        tensor = torch.load(input_path)
        print(f"Tensor shape: {tensor.shape}")

        if tensor.ndim != 4:
            print(
                f"Error: Expected 4D tensor (N, C, H, W), \
                    but got {tensor.ndim}D tensor."
            )
            sys.exit(1)

        if tensor.shape[1] != 3:
            print(
                f"Warning: Expected 3 channels (RGB), got {tensor.shape[1]}. \
                    Visualization might look wrong."
            )

        N = tensor.shape[0]
        if N == 0:
            print("Tensor is empty (0 frames).")
            return

        # Select frames
        if args.random and N > args.max_frames:
            indices = torch.randperm(N)[: args.max_frames]
            indices, _ = torch.sort(indices)  # Sort indices to keep temporal order
            subset = tensor[indices]
            print(f"Selected {args.max_frames} random frames.")
        elif N > args.max_frames:
            print(f"Limiting to first {args.max_frames} frames out of {N}.")
            subset = tensor[: args.max_frames]
        else:
            subset = tensor

        # Save grid
        vutils.save_image(
            subset, args.output, nrow=args.nrow, padding=2, normalize=False
        )
        print(f"Saved preview grid to {args.output}")

    except Exception as e:
        print(f"Error processing file: {e}")
        import traceback

        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
