name: Ruff

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    ruff-check:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.13"]

        steps:
            - uses: actions/checkout@v4
            - name: Setup Python ${{ matrix.python-version }} with uv
              uses: ./.github/actions/setup-python-with-uv
              with:
                  python-version: ${{ matrix.python-version }}
            # Update output format to enable automatic inline annotations.
            - name: Ruff check
              run: uv run ruff check --output-format=github .
